chore: Add Azure Pipelines for CI (Windows, Linux, Mac) (#1630), Fix async function serialization in Safari.
* Add azure pipelines CI.

* Publish test results.

* Enable coveralls

* Use Safari  for OSX browser tests.

* Adding missing lib files to karma (only Safari complained).

* Rename with dot so it gets better placed in order.

* Use ci instead of install, so we stick with package-lock.json

* Use npm test instead of mocha directly. It just needed a double -- escape.

* Move DISPLAY to Linux only, with value set just once.

* Use variables for DISPLAY, browser tests and coveralls.

* Simplify steps with a browser name variable.

* Run junit reporter on CI only.

* DISPLAY should be already an environment variable.

* Use vmImage for consistency with other OS.

* Don't use verbose npm@1 task.

* No need to setTimeout, let's `done` on the callback.

* Don't resume twice.
Check queue length on callback for safety, setTimeout may be delayed.

* Avoid time dependency, act on events instead.

* Avoid dependency on timing to final assertion.

* Rewrite test to avoid setTimeout

* Fix formatting.

* Make diff more significant (125+50 ~= 200)

* Make diff more significant to avoid race conditions.

* Wait a bit more so default 5 retries did happen.

* Make delays shorter to avoid "Timeout of 250ms exceeded"

* Shorten delay to avoid 200ms test timeout in browser tests.

* Shorten timeout to mitigate 200ms test timeout.

* Add more diff on delays to enforce test behavior.

* Make delays more significant to avoid race conditions.

* Stop using setTimeout and rely on events to push new items, so order is enforced.

* Fix async function serialization in Safari.

* Add more delay so 4 never completes before 3.

* Ensure 3 never completes before 4.

* Use drain instead of task count.
Trying to ensure done is called from Windows browser tests that fail frequently.

* Ensure 2 starts before 3 arrives.Avoid expected 'process 2 3' to equal 'process 2'

* Add retries to browser tests.

* Don't fail all on Mac & Windows browser tests.

* Ensure 3 happens before 2, it fails sparely on OSX.
AssertionError: expected [ 1, 2, 3 ] to deeply equal [ 1, 3, 2 ]

* Avoid unnecessary multilines.

* Use Edge for Windows browser tests.